### PR TITLE
feat(questionnaire): Update createNewAccount function to validate all user information and check if email is already in use

### PR DESCRIPTION
**Pull request by rethinkDeliriumRaj**
DO NOT MERGE YET

### CODE REVIEW

**Comment by rethinkdeliriumjack** [comment]
Looks good and makes sense. Thanks for cleaning up the relationship field.

**Comment by rethinkDeliriumRaj** [comment]
PREVIEW: https://rethink-delirium-upload-jc23z0erh-rethinkdeliriumraj.vercel.app/

**Comment by rethinkdeliriumjack** [comment]
There is no back button after creating account and creating care recipient and entering the pre-Stripe page

image

**Comment by rethinkdeliriumjack** [comment]
After putting in my LIVE card

I saw this error message for 2 seconds 
image

And then the real thank you page appeared. Good job on getting the payment to work though.

image

I also recognize that there are entries in both the Account and Patient tables in DynamoDB - great job

**Pull request merged**
