### PR TITLE
Removed "add reorienting messages button" from input home

### PR DESCRIPTION
**Pull request by rethinkdeliriumjack**

### CODE REVIEW

**Comment by rethinkdeliriumjack** [comment]
I better not have broken something already

**Comment by rethinkDeliriumRaj** [comment]
@rethinkdeliriumjack I saw you removed the button, can you also remove the pages and components linked to the feature?

**Comment by rethinkDeliriumRaj** [comment]
PR LGTM, checking Vercel output to verify if it works

**Comment by rethinkdeliriumjack** [comment]
Closing since #132 removed reorienting messages

**Pull request closed without merging**
